apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        otnipid/beauty-box-site: true
        the-99/beauty-box-site: true
        the-99/jx3-minikube: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        otnipid/beauty-box-site: merge
        the-99/beauty-box-site: merge
        the-99/jx3-minikube: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - the-99/jx3-minikube
        - otnipid/beauty-box-site
        - the-99/beauty-box-site
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - the-99/jx3-minikube
        - otnipid/beauty-box-site
        - the-99/beauty-box-site
      target_url: http://lighthouse-jx.192.168.49.2.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
